/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.63 (1.7.3)
 * Generated at: 2016-02-11 11:21:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class webBankingPage_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tags/Header.tag", Long.valueOf(1455188499019L));
    _jspx_dependants.put("/WEB-INF/custTags.tld", Long.valueOf(1455189395090L));
    _jspx_dependants.put("/WEB-INF/tags/BankForm.tag", Long.valueOf(1455189427635L));
    _jspx_dependants.put("/WEB-INF/tags/Footer.tag", Long.valueOf(1455189697614L));
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_ct_005fHeader_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_ct_005fBankFrom_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_ct_005fFooter_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }

  private boolean _jspx_meth_ct_005fHeader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:Header
    org.apache.jsp.tag.webHeader_tag _jspx_th_ct_005fHeader_005f0 = (new org.apache.jsp.tag.webHeader_tag());
    _jsp_instancemanager.newInstance(_jspx_th_ct_005fHeader_005f0);
    _jspx_th_ct_005fHeader_005f0.setJspContext(_jspx_page_context);
    _jspx_th_ct_005fHeader_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/BankingPage.tag(3,0) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_ct_005fHeader_005f0.setTitle("Banking page");
    _jspx_th_ct_005fHeader_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_ct_005fHeader_005f0);
    return false;
  }

  private boolean _jspx_meth_ct_005fBankFrom_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:BankFrom
    org.apache.jsp.tag.webBankForm_tag _jspx_th_ct_005fBankFrom_005f0 = (new org.apache.jsp.tag.webBankForm_tag());
    _jsp_instancemanager.newInstance(_jspx_th_ct_005fBankFrom_005f0);
    _jspx_th_ct_005fBankFrom_005f0.setJspContext(_jspx_page_context);
    _jspx_th_ct_005fBankFrom_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    _jspx_th_ct_005fBankFrom_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_ct_005fBankFrom_005f0);
    return false;
  }

  private boolean _jspx_meth_ct_005fFooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ct:Footer
    org.apache.jsp.tag.webFooter_tag _jspx_th_ct_005fFooter_005f0 = (new org.apache.jsp.tag.webFooter_tag());
    _jsp_instancemanager.newInstance(_jspx_th_ct_005fFooter_005f0);
    _jspx_th_ct_005fFooter_005f0.setJspContext(_jspx_page_context);
    _jspx_th_ct_005fFooter_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/BankingPage.tag(5,0) name = version type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_ct_005fFooter_005f0.setVersion("1.01");
    // /WEB-INF/tags/BankingPage.tag(5,0) name = projectName type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_ct_005fFooter_005f0.setProjectName("04.EnterpriseJavaBeansHomework");
    _jspx_th_ct_005fFooter_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_ct_005fFooter_005f0);
    return false;
  }
}
